plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3 
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - 'bin/*'
    - 'config/routes.rb'
    - 'vendor/'

Rails/StrongParametersExpect:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Rails/I18nLocaleTexts:
  Enabled: false 

RSpec:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*'